spring:
  application:
    name: genai-java-spring
  ai:
    openai:
      api-key: ${HUGGING_FACE_API_KEY} # ${OPEN_AI_API_KEY}
      base-url: https://router.huggingface.co # https://openrouter.ai/api
      chat:
        options:
          model: Qwen/Qwen2.5-7B-Instruct:together # gpt-4o
    ollama:
      base-url: http://localhost:11434
      chat:
        model: qwen3:0.6b
    google:
      genai:
        project-id: ${GOOGLE_PROJECT_ID}
        api-key: ${GEMINI_API_KEY}
        chat:
          options:
            model: gemini-2.0-flash-lite
server:
  port: 8081
logging:
  level:
    root: info
    com.genai.java.spring: info
    org.springframework.ai: info

kind: Application

app:
  ai:
    provider: ollama # gemini or openai or ollama

